version: '3'
services:
  node:
    image: node:13-slim
    container_name: node
    networks:
      - default
    volumes:
      - ./node_modules:/home/node/app/node_modules
      - .:/home/node/app/
    working_dir: /home/node/app